- meson.build
- src/frontend/driver.cpp
- src/frontend/lexer.l
- src/frontend/node.hpp
- src/frontend/parser.yy
- src/frontend/parser_test.cpp
The biggest change here is that we actually check the return value of the lexer and parser, which means that a number of things that were invalid are now actual errors.
I've also fixed a number of issues that I discovered by running most of the meson.build files from the main meson repo through the standalone parser:
* escape sequences in strings (but not triple strings yet)
* foreach loops with dictoinaries
* incorrect counting of lines
* using backslash to escape a newline
> Fix a number of issues with the parser

- src/options.cpp
* handle extra positional arguments (an error)
* document the --source-dir argument
> Fixups for the meson++ command line parser

- src/frontend/lexer.l
- src/frontend/parser.yy
- src/frontend/parser_test.cpp
With this the meson++ parser can correctly parse all of the meson.build files in the main meson repo that are supposed to be parsed (there are some that are supposed to fail).
Fixes #34
> Fix remaining parser issues for meson repo

- src/frontend/lexer.l
- src/frontend/parser_test.cpp
Previously an actual (not escaped) newline would cause the lexer to jam.
> lexer: handle newlines in triple strings correctly

- src/mir/ast_to_mir.cpp
- src/mir/ast_to_mir_test.cpp
- src/mir/mir.cpp
- src/mir/mir.hpp
- src/mir/passes/compilers.cpp
- src/mir/passes/join_blocks.cpp
- src/mir/passes/pruning.cpp
- src/mir/passes/walkers.cpp
- src/mir/passes_test.cpp
The current way that if lowering is done is completely broken. For one thing, nested if's don't work. For another the entire value of the SSAish only two possible outputs isn't really true. This work makes the IR slightly more complicated but more consistent. I've also commented some code that I couldn't remember how it worked, and tried to leave more useful comments this time.
> Rework if lowering from ast

- src/mir/ast_to_mir.cpp
- src/mir/ast_to_mir_test.cpp
- src/mir/mir.hpp
- src/mir/passes/join_blocks.cpp
- src/mir/passes/pruning.cpp
- src/mir/passes/walkers.cpp
- src/mir/passes_test.cpp
This is necessary for cross block optimizations to work, especially branch joining. Without this the joining pass could easily try to join two blocks where the child has two parents. This is additionally helpful in allowing us to do reverse traversals of the IR
> MIR: track blocks parents as well as their children

- src/mir/lower.cpp
- src/mir/meson.build
- src/mir/passes.hpp
- src/mir/passes/value_numbering.cpp
- src/mir/passes/walkers.cpp
- src/mir/passes_test.cpp
This adds a value numbering pass. All it does is go through and
annotations for which "version" of the variable this is. This doesn't
re-value something that's already been valued. Taht might prove to be
annoying, but I'm going to go with it for now.
If we do need to re-value, we probably need to write a "de-numbering"
pass to run before the value_numbering pass, due to revisiting the same
block twice.
Fixes #29
> mir/passes/value_numbering: introduce

- src/mir/passes/join_blocks.cpp
- src/mir/passes/pruning.cpp
- src/mir/passes/value_numbering.cpp
- src/mir/passes/walkers.cpp
This seemed like a good idea at the time, but it wasn't. Instead passes
that want to act on the same block multiple times should just do that
internally. This ports both branch_pruning and join_blocks to work this
way.
Fixes #55
> mir/passes: don't visit blocks twice with BlockWalker

- src/mir/passes/free_functions.cpp
Just a few cleanups to share some code between the StaticLibrary lowering code and the Executable code. This will also be useful to prevent duplication when SharedLibrary and SharedModules are introduced.
> Build target cleanups

- src/main.cpp
- src/mir/meson/meson.build
- src/mir/meson/state/state.cpp
- src/mir/meson/state/state.hpp
- src/mir/mir.hpp
- src/mir/passes/flatten.cpp
- src/mir/passes/free_functions.cpp
- src/mir/passes/private.hpp
- src/mir/passes/tests/free_functions_test.cpp
- src/util/log.cpp
- src/util/log.hpp
- tests/dsl/06 messages/meson.build
With the caveat that meson++ still flattens all inputs to the message family, unlike Meson.
Fixes #66
> Implement the message() family of functions

- src/main.cpp
- src/mir/ast_to_mir.cpp
- src/mir/ast_to_mir_test.cpp
- src/mir/lower.cpp
- src/mir/meson.build
- src/mir/meson/machines.hpp
- src/mir/meson/state/state.cpp
- src/mir/meson/state/state.hpp
- src/mir/mir.hpp
- src/mir/passes.hpp
- src/mir/passes/compilers.cpp
- src/mir/passes/constant_folding.cpp
- src/mir/passes/constant_propogation.cpp
- src/mir/passes/free_functions.cpp
- src/mir/passes/machines.cpp
- src/mir/passes/private.hpp
- src/mir/passes/program_objects.cpp
- src/mir/passes/tests/constant_propogation_test.cpp
- src/mir/passes/tests/free_functions_test.cpp
- src/mir/passes/threaded.cpp
- src/mir/passes/value_numbering.cpp
- src/mir/passes/walkers.cpp
- tests/dsl/01 subdir/meson.build
- tests/dsl/06 messages/meson.build
- tests/dsl/07 find_program/meson.build
This adds the found() method as well, and the assert() function. None of this is too useful on it's own yet, since we don't have any targets that consume them, but it's a first step towards custom_target, and it gives me a chance to put my idea for the biggest win that meson++'s architecture offers, threading.
The basic idea is this:
reduce the IR as much as possible, then run the threaded jobs (find_program, run_target?, dependency(), and many of the compiler methods), then return to the main loop. Because we have an IR, with a bit of carefulness we can do all of that in threads, making the tests very, very fast.
Fixes #24
> Add support for find_program

- src/frontend/parser.yy
- src/mir/ast_to_mir.cpp
- src/mir/ast_to_mir_test.cpp
- src/mir/passes/free_functions.cpp
- src/mir/passes/tests/free_functions_test.cpp
- tests/dsl/07 find_program/meson.build
This allows the `not` and `-` (unary, not subtractive) operator to be parsed into AST, and then converted into MIR, and lowered away.
> Implement unary ops

- src/mir/passes/free_functions.cpp
- src/mir/passes/private.hpp
- src/mir/passes/program_objects.cpp
Currently, on each object, for each function lowering method, we check if the thing is a function, then we check the holder, and the name of the function, returning if the current lowering function doesn't act on it. This is pretty inefficient, just in our very limited tests it adds about .01 seconds to the run time, and there area a *lot* of unimplemented functions and methods. The new code is not perfect, but it uses a dispatch function to avoid some of the overhead by only doing the variant extraction once, as well as the name and holder check once.
Fixes #87
> Refactor function lowering

- src/mir/lower.cpp
- src/mir/meson.build
- src/mir/mir.cpp
- src/mir/mir.hpp
- src/mir/passes.hpp
- src/mir/passes/argument_extractors.hpp
- src/mir/passes/constant_propogation.cpp
- src/mir/passes/dependency_objects.cpp
- src/mir/passes/free_functions.cpp
- src/mir/passes/private.hpp
- src/mir/passes/string_objects.cpp
- src/mir/passes/tests/free_functions_test.cpp
- src/mir/passes/threaded.cpp
- tests/dsl/10 dependency methods/meson.build
This only provides very basic declare dependency support, but it's a start. With this we can:
- call `declare_dependency()` and get a valid object
- call the `.found()` method
- call the `.name()` method
- call the `.version()` method
Fixes #16
> Initial support for declare_dependency

- meson.build
- subprojects/libpkgconfpp.wrap
Which has a fixed name so that pkg-config and fallback work correctly
> meson: use pkgconf++ 0.2.0

- src/mir/passes/threaded.cpp
Allows removing a bunch of std::ref calls.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
> replace function call with lambda

- src/mir/lower.cpp
- src/mir/meson.build
- src/mir/meson/machines.cpp
- src/mir/meson/machines.hpp
- src/mir/mir.cpp
- src/mir/mir.hpp
- src/mir/passes.hpp
- src/mir/passes/free_functions.cpp
- src/mir/passes/print.cpp
- tests/dsl/04 link static and exe/meson.build
This prints MIR data into a (mostly) human readable form before the first optimization loop, and and at the end of each loop after that. It's controlled by the `MESONPP_DEBUG_PRINT_MIR` environment variable. The format is inspired by NIX, and is in no way to be considered stable or suitable as any kind of interchange format.
> Add a MIR printer

- src/mir/passes/threaded.cpp
```
The lock guard objects were unnamed, therefore
they were immediately destroyed, thus they
did not keep the mutex locked during the scope
they were declared in. This was found by clang-tidy.
```
Fixes: 42a15e6eed641662d1ca418690eeeca4fc226a75 ("threaded: encapsulate locking for Job list completely")
> mir/passes/threaded: fix lock guards

- .github/workflows/codeql-analysis.yml
- .github/workflows/ubuntu.yml
Mostly, we just need to pin python at 3.10, because the version of Meson I want to stick with for the moment is broken on 3.11
> CI: update actions

- src/mir/passes/threaded.cpp
See commits messages for more details.
> mir/passes/threaded: find_program: correctly split PATH and ignore zero length components

- src/mir/meson/machines.hpp
This is a legit issue, not only was the target being initialized first, but both the host and the target values were moving the target field from the other one. This last part is obviously really bad.
> mir: fix warnings with PerMachine move-constructor

- .clang-tidy
- src/mir/lower.cpp
- src/mir/meson.build
- src/mir/passes.hpp
- src/mir/passes/custom_target_program_replacement.cpp
- src/mir/passes/tests/custom_target_program_replacement_test.cpp
- src/mir/passes/tests/lower_test.cpp
This is a pass that can be run once, in the early phase, to replace cases where the first argument to `custom_target` is a string, not a `file()`, `find_program()`, or `executable()`, and transform it into a `find_program()` call.
Fixes: #86
> mir: replace custom_target string command with find_program call

- src/backends/ninja/ninja.cpp
Correctly handle `#` and `$`
Fixes: #136
> backends/ninja: fix escaping rules

- src/mir/mir.cpp
- src/mir/mir.hpp
- src/mir/passes/argument_extractors.hpp
- src/mir/passes/free_functions.cpp
- src/mir/passes/string_objects.cpp
- src/mir/passes/tests/custom_target_program_replacement_test.cpp
- src/mir/passes/threaded.cpp
Throw errors when the types are invalid, be more specific about missing vs empty arrays.
> Clean up argument extractors

- src/mir/ast_to_mir.cpp
- src/mir/mir.cpp
- src/mir/mir.hpp
- src/mir/passes/compilers.cpp
I initially considered simply looking for functions with `meson` as their held object and replacing them with some kind of free function type, however, meson allows for this:
```meson
x = meson
cc = x.get_compiler('c')
```
Which means we have to be able to const-propagate that assignment to resolve the meson namespace.
> mir: Introduce a Meson object for the `meson` namespace
